env = "dev"
region = "eu-north-1"
ami_id = "ami-04cdc91e49cb06165"
instance_type = "t3.micro"
key_name   = "frontend-key"
key_path = "/home/keretdodor/Desktop/KEYS/keypairing1.pub"
bucket_name = "becks-bucket-ever-dos"
az = "b"