apiVersion: apps/v1
kind: Deployment
metadata:
  name: netflix-catalog
  labels:
    app: netflix-catalog-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: netflix-catalog-demo
  template:
    metadata:
        labels:
          app: netflix-catalog-demo
    spec:
      containers:
      - name: api
        image: keretdodor/netflix-catalog:v1.0.5

---

apiVersion: v1
kind: Service
metadata:
  name: nextflix-catalog-service
spec:
  selector:
    app: netflix-catalog-demo
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080      