apiVersion: apps/v1
kind: Deployment
metadata:
  name: netflix-frontend-prod
  labels:
    app: netflix-frontend-prod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: netflix-frontend-prod
  template:
    metadata:
        labels:
          app: netflix-frontend-prod
    spec:
      containers:
      - name: api
        image: keretdodor/netflix-frontend:v1.0.37
        env:
          - name: MOVIE_CATALOG_SERVICE
            value: "http://nextflix-catalog-service:8080"

--- 

apiVersion: v1
kind: Service
metadata:
  name: nextflix-frontend-service
spec:
  selector:
    app: netflix-frontend-prod
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000   