apiVersion: apps/v1
kind: Deployment
metadata:zz
  name: netflix-catalog-dev
  labels:
    app: netflix-catalog-dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: netflix-catalog-dev
  template:
    metadata:
        labels:
          app: netflix-catalog-dev
    spec:
      containers:
      - name: api
        image: keretdodor/netflix-catalog:latest

---

apiVersion: v1
kind: Service
metadata:
  name: nextflix-catalog-service
spec:
  selector:
    app: netflix-catalog-dev
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080      