apiVersion: apps/v1
kind: Deployment
metadata:zz
  name: netflix-catalog-prod
  labels:
    app: netflix-catalog-prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: netflix-catalog-prod
  template:
    metadata:
        labels:
          app: netflix-catalog-prod
    spec:
      containers:
      - name: api
        image: keretdodor/netflix-catalog:latest

---

apiVersion: v1
kind: Service
metadata:
  name: nextflix-catalog-service
spec:
  selector:
    app: netflix-catalog-prod
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080      